apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: registry.k8s.io/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir:
      sizeLimit: 500Mi



## example-2 it uses the medium memory for emptyDir which uses ram as storage
# apiVersion: v1
# kind: Pod
# metadata:
#   name: test-pd
# spec:
#   containers:
#   - image: registry.k8s.io/test-webserver
#     name: test-container
#     volumeMounts:
#     - mountPath: /cache
#       name: cache-volume
#   volumes:
#   - name: cache-volume
#     emptyDir:
#       sizeLimit: 500Mi
#       medium: Memory