apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memos
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
---
apiVersion: v1
kind: Pod
metadata:
  name: memos
  labels:
    app: memos
spec:
  containers:
    - name: memos
      image: elestio/memos
      env:
        - name: MEMOS_PORT
          value: "5230"
        - name: MEMOS_DATA
          value: "/data"
      ports:
        - containerPort: 5230
          name: http
      volumeMounts:
        - name: memo
          mountPath: /data
  volumes:
    - name: memo
      persistentVolumeClaim:
        claimName: memos
---
apiVersion: v1
kind: Service
metadata:
  name: memos
spec:
  type: NodePort
  selector:
    app: memos
  ports:
    - protocol: TCP
      port: 5230
      targetPort: 5230
      nodePort: 30523
