apiVersion: v1 
kind: Service 
metadata:
  name: nomad-svc
spec:
  selector:
    matchLabels:
    app: nomad
  ports:
    - name: http
      protocol: TCP
      port: 4646
      targetPort: 4646
    - name: rpc
      protocol: TCP
      port: 4647
      targetPort: 4647
  type: NodePort