apiVersion: v1
kind: Service
metadata:
  name: clusterip
spec:
  type: ClusterIP #(used for internal access within the cluster)
  selector:
    app: nginx ## this exposes ngixn pods to the outside world
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 80
     
   