apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
spec:
  type: LoadBalancer #(used for external access)
  selector:
    app: nginx ## this exposes ngixn pods to the outside world
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 80
  