apiVersion: v1
kind: Pod
metadata:
  name: test 
  namespace: resources
spec:
  containers:
  - name: cpu-memory-test
    image: polinux/stress 
    resources:
      requests: 
        memory: "200G"
         #   cpu: 
      limits:
        memory: "200G"
        #cpu: 
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "400M", "--vm-hang","1"]